#ifndef PKSMCORE_CONFIG
#define PKSMCORE_CONFIG

#define _PKSMCORE_LANG_FOLDER "nitro:/i18n/"
#define _PKSMCORE_GETLINE_FUNC __getline
#define _PKSMCORE_DISABLE_THREAD_SAFE_RANDOM

#define _PKSMCORE_EXTRA_LANGUAGES BRH, IND, LIT, POL, POR, RUS


#endif