name: Build pkmn-chest

on:
  push:
    branches-ignore: [translation]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build pkmn-chest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Install tools
        run: |
          curl -L https://github.com/Universal-Team/bmp2ds/releases/download/v1.0.0/bmp2ds-linux -o bmp2ds
          chmod +x bmp2ds
          mv bmp2ds /usr/local/bin
      - name: Build
        id: build
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=$DEVKITPRO/devkitARM

          make all dsi

          sudo mv tools-linux/make_cia /usr/local/bin
          make cia

          mkdir -p ~/artifacts
          cp pkmn-chest.* ~/artifacts
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: build
